#!/bin/bash -x

if ! lsb_release -i | grep -q Ubuntu; then
    echo "This is not an Ubuntu build Env!"
    exit 1
fi

cp solidfire/kernel.config .config

export CC=/usr/bin/gcc-4.8.1-p1
export CXX=/usr/bin/g++-4.8.1-p1

make -j $(($(nproc --all) + 1)) deb-pkg LOCALVERSION=-$(git rev-parse --abbrev-ref HEAD)-$(git describe --tags --abbrev=6 --dirty) KDEB_PKGVERSION=$(make kernelversion)
